### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by MaLeVoLenT1** [laravel-notification-channels/discord#14]
I wanted to test the bot using your code. In your example you simply have $ composer test. I have no clue how to start this although I got it unto my discord server it doesn't stay.

**Comment by codyphobe** [comment]
Running `composer test` will run PHPUnit to make sure the code does what it's expected to do (though the tests might not be that great, I was never really great at making them).

After setting up the bot it should be on your server but in an offline state. This is because the bot only connects when it sends a notification, it doesn't run all the time because it doesn't need to and doing so would require a script to be running all the time.

If you wanted to actually test the bot's notifications, you'll need an Eloquent model with a `routeNotificationForDiscord` method that returns the ID of the Discord channel you want to post the notifications to. Once that's setup you can make a new notification that uses the `DiscordChannel` class in the notification's `via` method and return a `DiscordMessage` in the `toDiscord` method. You can find an example notification in the [Usage](https://github.com/laravel-notification-channels/discord#usage) section of the readme.
