### ISSUE TITLE
When deployed on hosting

### ISSUE THREAD

**Issue by RolandVerner** [laravel-notification-channels/discord#17]
When i deployed on hosting i got an error
On PC all works

NotificationChannels \ Discord \ Exceptions \ CouldNotSendNotification
Discord responded with an HTTP error: 401: 401: Unauthorized

**Comment by codyphobe** [comment]
Can you post the full stack trace?

**Comment by rolandverner** [comment]
I do the connect on the hosting via shell access but it not helps

**Comment by rolandverner** [comment]
what i  can do if the artisan discord:setup on host not works

**Comment by codyphobe** [comment]
Do you get an error when running `discord:setup` on your server?

**Comment by rolandverner** [comment]
![image](https://user-images.githubusercontent.com/12708415/34301165-17e9d150-e734-11e7-828f-0d53902fe54f.png)

**Comment by cryoten** [comment]
If you haven't solved this, the token is the Bot's token rather than the App's. Prior to running `php artisan discord:setup` I would get 401 Unauthorized when using the App's token and 400 Unauthorized with the Bot's token. While using the Bot's token, I ran `php artisan discord:setup` and my problems were fixed.

Make sure you have the right token.

**Comment by wast** [comment]
Close this. No response.
